name: "Test"
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  tests:
    strategy:
      matrix:
        os: [ubuntu-18.04, macos-10.15]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v1
    - uses: './.github/actions/nix'
      with:
        CACHIX_SIGNING_KEY: ${{ secrets.CACHIX_SIGNING_KEY }}
    - name: "Check Haskell formatting"
      run: nix run -c "script/fmt -c"
    - name: "Run tests"
      run: ./script/test
